In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [8]:
arr=np.array(my_list)
arr

array([1, 2, 3])

from numpy import array

In [11]:
from numpy import array
from math import sqrt

In [15]:
height=[4.12,5.26,6.75]
weight=[60.4,70.3,80.1]
bmi= weight/height**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [16]:
np_height= np.array(height)
np_weight= np.array(weight)

In [20]:
bmi=np_weight/np_height**2
bmi

array([3.55829956, 2.54087814, 1.75802469])

In [23]:
x=np.arange(1,10)

In [24]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
len(x)

9

In [29]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [30]:
arr= np.arange(0,11)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[-5]

6

In [1]:
import pandas as pd

In [5]:
inputt_file = 'data_multivar_nb.txt'
data = pd.read_csv(inputt_file)
data

2.18  0.57  0
0    4.13  5.12  1
1    9.87  1.95  2
2    4.02 -0.80  3
3    1.18  1.03  0
4    4.59  5.74  1
..    ...   ... ..
394  3.29 -0.30  3
395  0.55  0.70  0
396  4.40  6.75  1
397  8.71  3.38  2
398  6.12 -1.80  3

[399 rows x 3 columns]

In [4]:
data.describe()

2.18        0.57           0
count  399.000000  399.000000  399.000000
mean     4.774436    2.148170    1.503759
std      2.676069    2.701223    1.118309
min     -0.390000   -2.820000    0.000000
25%      2.775000    0.100000    1.000000
50%      4.610000    1.950000    2.000000
75%      6.695000    4.500000    2.500000
max     10.620000    7.800000    3.000000

In [6]:
data.head(5)

2.18  0.57  0
0  4.13  5.12  1
1  9.87  1.95  2
2  4.02 -0.80  3
3  1.18  1.03  0
4  4.59  5.74  1